name: Docker Package and Sign

on:
  workflow_dispatch:

jobs:
  package-sign:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/signed-app:${{ github.sha }} .

      - name: Push Image
        run: |
          docker push ghcr.io/${{ github.repository }}/signed-app:${{ github.sha }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1

      - name: Sign Docker Image
        run: |
          cosign sign --yes ghcr.io/${{ github.repository }}/signed-app:${{ github.sha }}

      - name: Verify Image Signature
        run: |
          cosign verify ghcr.io/${{ github.repository }}/signed-app:${{ github.sha }}
