name: Build and Sign

on:
  workflow_dispatch:

jobs:
  build-sign:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Archive artifact
        run: |
          tar -czf app.tar.gz app/

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1

      - name: Sign artifact
        run: |
          cosign sign-blob --yes --output-signature app.sig app.tar.gz

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: signed-artifact
          path: |
            app.tar.gz
            app.sig
